source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'osx-tests', :exclusive => true do
  platform :osx, '10.10'
  pod "cmark-bridge", :path => "../"
end

target 'ios-tests', :exclusive => true do
  pod "cmark-bridge", :path => "../"
end
